ACMbudget/urls.py
from django.contrib import admin
from django.urls import path
from budget import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('index/userinfo', views.showuser, name='userinfo'),
    path('creuserajax', views.ajax_cre_user, name='ajax_cre_user'),
    path('deuserajax', views.ajax_de_user, name='ajax_de_user'),
    path('upuserajax', views.ajax_up_user, name='ajax_up_user'),
    path('ajax_se_user', views.ajax_se_user, name='ajax_se_user'),
    path('index', views.creindex, name='creindex'),
    path('ajax_up_own', views.ajax_up_own, name='ajax_up_own'),
    path('unlogin', views.unlogin, name='unlogin'),

    path('index/cjys', views.el_list, name='eltail'),
    path('index/getcitylist_provinceID<int:provinceID>', views.city_list),
    path('index/create', views.cre, name='cre'),
    path('index/<int:e_id>', views.showele, name='selel'),
    path('selel2', views.selel2, name='selel2'),
    path('ajax_up_ele', views.ajax_up_ele, name='ajax_up_ele'),
    path('ajax_de_ele', views.ajax_de_ele, name='ajax_de_ele'),

    path('index/zzjs', views.ul_list, name='ul_list'),
    path('index/zzys/<int:u_id>', views.showult, name='showult'),
    path('index/zzys/cre<int:e_id>', views.cre_ult, name='cre_ult'),
    path('ajax_cre_ult', views.ajax_cre_ult, name='ajax_cre_ult'),
    path('ajax_up_ult', views.ajax_up_ult, name='ajax_up_ult'),
    path('ajax_de_ult',views.ajax_de_ult, name='ajax_de_ult'),
    path('ajax_se_ult', views.ajax_se_ult, name='ajax_se_ult'),

    path('index/sjzd', views.account_list, name='account_list'),
    path('index/sjzd/cre<int:u_id>', views.cre_account, name='cre_account'),
    path('ajax_cre_account', views.ajax_cre_account, name='ajax_cre_account'),
    path('index/sjzd/<int:acco_id>', views.show_account, name='show_account'),
    path('ajax_up_account', views.ajax_up_account, name='ajax_up_account'),
    path('ajax_de_account', views.ajax_de_account, name='ajax_de_account'),
    path('ajax_se_account', views.ajax_se_account, name='ajax_se_account'),
    path('index/sjzd/year<int:year>', views.accountyear, name='accountyear'),

    path('insdex/qt<int:type>', views.show_qt, name='show_qt'),
    path('ajax_se_qt', views.ajax_se_qt, name='ajax_se_qt'),
    path('ajax_cre_qt', views.ajax_cre_qt, name='ajax_cre_qt'),
    path('ajax_de_qt', views.ajax_de_qt, name='ajax_de_qt'),
]

budget/forms.py
import json
from datetime import datetime, timedelta
from django import forms
from .models import Admi,CName

class LoginForm(forms.Form):
    username = forms.CharField(label='账号', max_length=15, required=True, min_length=3,
                               widget=forms.TextInput(),
                               error_messages={
                                   'required': '请填写你的用户名',
                                   'max_length': '最多只能输入15个字符',
                                   'min_length': '至少输入3个字符'})
    password = forms.CharField(label='密码', max_length=20, min_length=3, required=True,
                               widget=forms.PasswordInput(),
                               error_messages={
                                   'required': '请输入密码',
                                   'max_length': '最多只能输入20个字符',
                                   'min_length': '至少输入3个字符'},
                               )
    def clean_username(self):
        user = self.cleaned_data['username']
        try:
            UserModal = Admi.objects.get(name=user)
            return user
        except:
           raise forms.ValidationError("账号不存在")

class CreForm(forms.Form):
    with open('static/json/city.json', 'rb') as f:
        city = json.load(f)
    PROVINCE_CHOICES = []
    CITY_CHOICES = []
    i = 1
    j = 1
    for ci in city.keys():
        PROVINCE_CHOICES.append([i, ci])
        for cit in city[ci]:
            CITY_CHOICES.append([j, cit])
            j += 1
        i += 1
    nty = forms.CharField(label='比赛类型', initial=2,
                           widget=forms.Select(choices=((1, 'ICPC'), (2, 'CCPC'),), attrs={'class': 'form-control'}))
    city = forms.ChoiceField(label='选择市',choices=CITY_CHOICES,
                             widget=forms.Select( attrs={'class': 'select form-control'}))
    province = forms.ChoiceField(choices=PROVINCE_CHOICES, label='选择省',
        widget=forms.Select(attrs={'class': 'select form-control', 'onChange': 'getCityOptions(this.value)'}))

    teachernum = forms.IntegerField(label='老师数量',min_value=1, max_value=50,
                                    widget=forms.NumberInput(attrs={'class': 'form-control'}))
    teamnum = forms.IntegerField(label='队伍数量', min_value=1, max_value=50,
                                 widget=forms.NumberInput(attrs={'class' : 'form-control'}))
    girlnum = forms.IntegerField(label='女性数量', min_value=0, max_value= 50,
                                 widget=forms.NumberInput(attrs={'class' : 'form-control'}))
    starttime = forms.DateTimeField(label='到达时间', widget=forms.TextInput(attrs={'class': 'form-control datetimepicker'}))
    endtime = forms.DateTimeField(label='回程时间', widget=forms.TextInput(attrs={'class': 'form-control datetimepicker'}))
    allo = forms.FloatField(label='补贴', widget=forms.TextInput(attrs={'class' : 'form-control', 'value': '100'}),)
    apply = forms.FloatField(label='报名费', widget=forms.TextInput(attrs={'class' : 'form-control', 'value': '1500'}))



budget/views.py
import json
from datetime import datetime, timedelta

from django.forms import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, render_to_response, get_object_or_404
from .models import Eleb, Admi, STra, ETra, SAir, EAir, Acc, CName, LoginAdmi, Ultb, Account
from .forms import LoginForm, CreForm
from django.db.models import F, Q
from django.db.models import Max, Avg, F, Q, Min, Count, Sum
from .tra import creTra
from .air import creAir
from .hotel import ceAcc

class DateEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj,datetime):
            return obj.strftime("%Y-%m-%d %H:%M:%S")
        else:
            return json.JSONEncoder.default(self,obj)

def login(request):
    if request.method == 'POST':
        userform = LoginForm(request.POST)
        if userform.is_valid():
            username = userform.cleaned_data['username']
            password = userform.cleaned_data['password']
            try:
                user = Admi.objects.get(name=username, password=password)
                LoginAdmi.objects.all().delete()
                us = LoginAdmi.objects.create(user=user)
                us.save()
                cnam = CName.objects.all()
                return render_to_response('index.html', {'user': user, 'cnam': cnam})
            except:
                userform = LoginForm()
                return render_to_response('login.html', {'userform': userform, 'pass_error': True})
    else:
        userform = LoginForm()
    return render_to_response('login.html', {'userform': userform, 'pass_error': False})
def creindex(request):
    user = LoginAdmi.objects.all()[0].user
    if user:
        cnam = CName.objects.all()
        return render_to_response('index.html', {'user': user, 'cnam': cnam})
    else:
        return render_to_response('login.html')
def showuser(request):
    users = LoginAdmi.objects.all()
    user = users[0].user
    userinfo = Admi.objects.all()
    return render_to_response('userinfo.html', {'userinfo': userinfo, 'user': user})
def ajax_cre_user(request):
    if request.is_ajax():
        username = request.POST['username']
        data = {'if_succes': True}
        try:
            User_error = Admi.objects.get(name=username)
            data['if_succes'] = False
            data = json.dumps(data)
            return HttpResponse(data)
        except:
            password = request.POST['password']
            ty = request.POST['ty']
            nu = Admi.objects.create(name=username, password=password, ty=ty)
            nu.save()
            data = json.dumps(data)
            return HttpResponse(data)
def ajax_de_user(request):
    if request.is_ajax():
        de_idlist = request.POST.getlist('de_idlist')
        user_id = LoginAdmi.objects.all()[0].user.pk
        user_id = str(user_id)
        data = {'de_succes': True}
        for de_id in de_idlist:
            if (de_id == user_id):
                data['de_succes'] = False
            else:
                try:
                    Admi.objects.get(pk=de_id).delete()
                except:
                    data['de_succes'] = False
        data = json.dumps(data)
        return HttpResponse(data)
def ajax_up_user(request):
    if request.is_ajax():
        tp = request.POST['tp']
        oldele = request.POST['oldele']
        newele = request.POST['newele']
        if tp == '1':
            Admi.objects.filter(name=oldele).update(name=newele)
        elif tp == '2':
            Admi.objects.filter(name=oldele).update(password=newele)
        else:
            if newele == '总教练':
                Admi.objects.filter(name=oldele).update(ty=True)
            else:
                Admi.objects.filter(name=oldele).update(ty=False)
        data = json.dumps({'tp': tp})
        return HttpResponse(data)
def ajax_se_user(request):
    if request.is_ajax():
        username = request.POST['username']
        users = LoginAdmi.objects.all()
        user = users[0].user
        userinfo = Admi.objects.get(name=username)
        dd = {'use_pk': userinfo.pk, 'user_ty': user.ty, 'username': userinfo.name, 'usepas': userinfo.password,
              'usty': userinfo.ty}
        data = json.dumps(dd)
        return HttpResponse(data)
def ajax_up_own(request):
    if request.is_ajax():
        user_id = LoginAdmi.objects.all()[0].user.pk
        password = request.POST['password']
        Admi.objects.filter(pk=user_id).update(password=password)
        data = json.dumps({'up_succes': True})
        return HttpResponse(data)
def unlogin(request):
    LoginAdmi.objects.all().delete()
    return render_to_response('unlog.html')

def se_traion(tratp, st, et, site):
    st1 = st - timedelta(days=1)
    et1 = et + timedelta(days=1)
    if tratp:
        strtraion = STra.objects.filter(etime__gte=st1, site=site).filter(etime__lte=st, site=site)
        endtraion = ETra.objects.filter(stime__gte=et, site=site).filter(stime__lte=et1, site=site)
    else:
        strtraion = SAir.objects.filter(etime__gte=st1, site=site).filter(etime__lte=st, site=site)
        endtraion = EAir.objects.filter(stime__gte=et, site=site).filter(stime__lte=et1, site=site)
    return (strtraion, endtraion)
def el_list(request):
    elelist = Eleb.objects.all()
    years = []
    for ele in elelist:
        if ele.name[:4] not in years:
            years.append(ele.name[:4])
    sorted(years);
    return render_to_response('cjys.html', {'elelist': elelist, 'years': years})
def jiaotong1(stime, etime, site):
    (strtraion, endtraion) = se_traion(True, stime, etime, site)
    (strair, endair) = se_traion(False, stime, etime, site)
    train = {}
    pr = 0
    for tra in strtraion:
        if (pr < tra.price):
            train['st_train'] = tra
            pr = tra.price
    pr = 0
    for tra in endtraion:
        if (pr < tra.price):
            train['end_train'] = tra
            pr = tra.price
    pr = 0
    for air in strair:
        if (pr < air.price):
            train['st_air'] = air
            pr = air.price
    pr = 0
    for air in endair:
        if (pr < air.price):
            train['end_air'] = air
            pr = air.price
    return train
def city_list(request, provinceID):
    with open('static/json/city.json', 'rb') as f:
        citys = json.load(f)
    i = 1
    j = 1
    cit = ''
    for ci in citys.keys():
        if (i == provinceID):
            cit = ci
            break
        j += len(citys[ci])
        i += 1
    citys = citys[cit]
    cit_list = {'star': j, 'end': j + len(citys)}
    return HttpResponse(json.dumps(cit_list))
def pricelist(ele):
    elist = {}
    elist['name'] = ele.name
    elist['teachernum'] = ele.tecnum
    elist['teamnum'] = ele.teanum
    elist['studentnum'] = ele.teanum * 3
    elist['feanum'] = ele.fnum
    elist['studentdays'] = (ele.etr_id.etime - ele.str_id.stime).days + 1
    elist['stuholdays'] = (ele.etr_id.stime - ele.str_id.etime).days + 1
    elist['ty'] = False
    if ele.eai_id:
        elist['ty'] = True
    if elist['ty']:
        elist['teacherdays'] = (ele.eai_id.etime - ele.sai_id.stime).days + 1
        elist['teajoldays'] = (ele.eai_id.stime - ele.sai_id.etime).days + 1
        elist['teas_air'] = ele.sai_id
        elist['teae_air'] = ele.eai_id
        elist['teacs_pri'] = ele.sai_id.price * elist['teachernum']
        elist['teace_pri'] = ele.eai_id.price * elist['teachernum']

    else:
        elist['teacherdays'] = elist['studentdays']
        elist['teajoldays'] = elist['stuholdays']
        elist['teas_tra'] = ele.str_id
        elist['teae_tra'] = ele.etr_id
        elist['teacs_pri'] = ele.str_id.price * elist['teachernum']
        elist['teace_pri'] = ele.etr_id.price * elist['teachernum']
    elist['stus_tra'] = ele.str_id
    elist['stue_tra'] = ele.etr_id
    elist['stus_pri'] = ele.str_id.price * elist['studentnum']
    elist['stue_pri'] = ele.etr_id.price * elist['studentnum']
    elist['acc'] = ele.ac_id
    elist['stu_acc'] = (elist['feanum'] + 1) // 2 + (elist['studentnum'] - elist['feanum'] + 1) // 2
    elist['tea_acc'] = elist['teachernum'] // 2
    if elist['teachernum'] % 2:
        if (elist['studentnum'] - elist['feanum'] + 1) % 2 == 0:
            elist['tea_acc'] += 1
    elist['stu_accpr'] = elist['stu_acc'] * ele.ac_id.price * (elist['stuholdays'] - 1)
    elist['tea_accpr'] = elist['tea_acc'] * ele.ac_id.price * (elist['teajoldays'] - 1)
    elist['allo'] = ele.allo
    elist['apply'] = ele.apply
    elist['stu_pri'] = elist['stus_pri'] + elist['stue_pri'] + elist['stu_accpr'] + ele.apply * elist['teamnum']
    elist['tea_pri'] = elist['teacs_pri'] + elist['teace_pri'] + elist['tea_accpr'] + ele.allo * elist['teajoldays'] * \
                       elist['teachernum']
    elist['price'] = elist['stu_pri'] + elist['tea_pri']
    elist['user'] = ele.ad_id.name
    return elist
def ge_nums():
    tenums = []
    teannum = []
    felnum = [0]
    for i in range(1, 10):
        tenums.append(i)
        teannum.append(i)
        felnum.append(i)
    for i in range(10, 20):
        teannum.append(i)
        felnum.append(i)
    nums = {'tenums': tenums, 'teannum': teannum, 'felnum': felnum}
    return nums
def get_price(stime, etime, site, allo):
    train = jiaotong1(stime, etime, site)
    acc1 = Acc.objects.filter(site=site)
    accc = {}
    tem = 0
    for ac in acc1:
        if (tem < ac.price):
            accc['acc'] = ac
            tem = ac.price
    price1 = 0
    if 'st_air' in train:
        tday1 = (train['end_air'].stime - train['st_air'].etime).days
        price1 = tday1 * accc['acc'].price
        tday1 = (train['end_air'].etime - train['st_air'].stime).days + 1

budget/templates/accou.html
{% extends 'base.html' %}
{% block title %}
    实际账单
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-2 col-md-offset-0">
            <span class="button-dropdown" data-buttons="dropdown">
                <button class="button button-rounded">
                    创建 <i class="fa fa-caret-down"></i>
                </button>

                <ul class="button-dropdown-list is-below">
                    {% for cre_a in crealist %}
                    <li class="button-dropdown-divider">
                        <a href="{% url 'cre_account' cre_a.ul_id.pk %}">{{ cre_a.ul_id.name }}</a>
                    </li>
                    {% empty %}
                    <div class="errorlist"><li>请先创建最终预算表哦</li></div>
                {% endfor %}
                </ul>

            </span>
        </div>
        <div class="col-md-3">
        <span class="button-dropdown" data-buttons="dropdown">
                <button class="button button-rounded">
                    年度总结 <i class="fa fa-caret-down"></i>
                </button>
                <ul class="button-dropdown-list is-below">
                     {% for year in years %}
                    <li class="button-dropdown-divider">
                        <a href="{% url 'accountyear' year %}">{{ year }}</a>
                    </li>
                    {% empty %}
                    <div class="errorlist"><li>没有账单哟</li></div>
                {% endfor %}
                </ul>

            </span>
        </div>
        <div class="col-md-7">
                <div class="form-group form-inline">
                    <label for="sel_year">年份:</label>
                    <select class="form-control show-tick selectpicker" id="sel_year">
                        <option value=""></option>
                        {% for year in years %}
                            <option value={{ year }}>{{ year }}</option>
                        {% endfor %}
                    </select>
                    <label for="sel_city">城市:</label>
                    <input class="form-control" id="sel_city" style="width: 80px">
                    <label for="sel_name">比赛名称:</label>
                    <input class="form-control" id="sel_name" style="width: 100px">
                    <button class="btn btn-default" id="get_sele">查询</button>
                </div>

        </div>
    </div>
    <div class="col-md-12 row">
        <hr/>
    </div>
    <div row>
        <div class="col-md-10 row col-md-offset-0" id="show_elelist">
            {% for acco in acclist %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href={% url 'show_account' acco.pk %}>{{ acco.name }}实际账单</a>
                    </div>
                </div>
            {% empty %}
                <p>还没有实际账单哟</p>
            {% endfor %}
        </div>
    </div>
     <script>
        $('#get_sele').click(function () {
            var year = $('#sel_year').val();
            if ($.trim($("#sel_city").val()).length == 0) {
                var site = '';
            } else {
                var site = $('#sel_city').val();
            }
            if ($.trim($("#sel_name").val()).length == 0) {
                var name = '';
            } else {
                var name = $('#sel_name').val();
                alert(name);
            }
            $.ajax({
                type: 'POST',
                url: "{% url 'ajax_se_ult' %}",
                traditional: true,
                dataType: "json",
                data: {year: year, site: site, name: name},
                success: function (data) {
                    $('#show_elelist').empty();
                    $.each(data, function (i, item) {
                        $('#show_elelist').append("<div class=\"panel panel-default\">\n" +
                            "<div class=\"panel-body\">\n" +
                            "<a href='sjzd/" + item.el_id + " '>" + item.nam + "实际账单</a>\n" +
                            "</div>\n" +
                            "</div>");
                    });
                }
            })
        })
    </script>
{% endblock %}

budget/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/ma.css" rel="stylesheet">
    <script src="/static/js/jquery-3.4.1.min.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
    <script src="/static/bootstrap-3.3.7/js/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
    <link href="/static/bootstrap-3.3.7/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <link href="/static/css/buttons.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <script src="/static/js/buttons.js"></script>
    <link href="/static/bootstrap-3.3.7/css/bootstrap-select.min.css" rel="stylesheet">
    <script src="/static/bootstrap-3.3.7/js/bootstrap-select.min.js"></script>
    <script src="/static/bootstrap-3.3.7/js/defaults-zh_CN.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'creindex' %}">ACM预算系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'eltail' %}">初始预算</a></li>
                <li><a href="{% url 'ul_list' %}">最终预算</a></li>
                <li><a href="{% url 'account_list' %}">实际账单</a></li>
                <li class="dropdown">
                    <a id="se_qt" data-toggle="dropdown" href="#">其它
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'show_qt' 1 %}">出发车次</a></li>
                        <li><a href="{% url 'show_qt' 2 %}">回程车次</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'show_qt' 3 %}">出发航班</a></li>
                        <li><a href="{% url 'show_qt' 4 %}">回程航班</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'show_qt' 5 %}">酒店</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 sidebar">
            <div class="text-center">
                <ul class="nav nav-sidebar">
                    <li>
                        <img src="../../static/images/touxiang.jpg" class="img-circle"
                             style="width: 110px;height: 110px">
                        <h3 style="color: #981a77">欢迎您！</h3>
                        <div class="list-op" id="list-op">
                            <button class="button button-tiny button-pill button-inverse" id="up_uu">修改
                            </button>
                            <a href="{% url 'unlogin' %}" class="button button-pill button-tiny button-inverse">登出</a>
                        </div>
                    </li>
                    <li>
                        <div class="col-md-10 col-md-offset-1" id="up_user" style="padding-top: 10px" hidden>
                            <div class="row">
                                <input class="form-control" style="width: 150px;" placeholder="密码"
                                       id="uspassword" maxlength="15">
                                <ul class="errorlist">
                                    <li id="pa_error" hidden>密码长度不能小于3个字</li>
                                </ul>
                            </div>
                            <div class="row" style="padding-top: 5px">
                                <button class="form-control" style="width: 150px;" id="get_up">提交</button>
                            </div>
                        </div>
                    </li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a class="text-nowrap" href="{% url 'userinfo' %}">用户信息</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    $('#up_uu').click(function () {
        $('#up_user').show();
    });
    $('#get_up').click(function () {
        if ($("#uspassword").val().length < 3){
            $('#pa_error').show();
            $('#uspassword').val('');
            return
        }
        var pa = $("#uspassword").val();
        $.ajax({
            type: "POST",
            url: "{% url 'ajax_up_own' %}",
            data: {password: pa},
            dataType: "json",
            success:function (data) {
                if (data.up_succes){
                    alert('密码修改成功');
                    window.location.reload()
                }
            }
        });
    })
</script>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    {% block content %}{% endblock %}
</div>
</body>
</html>

budget/templates/create.html
{% extends 'base.html' %}
{% block title %}
    初始预算创建
{% endblock %}
{% block content %}
    <hr>
    <div class="col-md-offset-2">
        {% if creerroe %}
            <ul class="errorlist">
                <li class="error text-center">这个初始预算已经被创建了哟</li>
            </ul>
            <hr>
        {% endif %}
        <script>
            function getCityOptions(province_id) {
                $.ajax({
                    type: 'GET',
                    url: "getcitylist_provinceID" + province_id,
                    dataType: 'json',
                    success: function (data) {
                        for (var i = 1; i < 392; i++)
                            $("#id_city option[value=" + i + "]").show();
                        $("#id_city").val(data['star']);
                        for (var i = 1; i < data['star']; i++)
                            $("#id_city option[value=" + i + "]").hide();
                        for (var i = data['end']; i < 392; i++)
                            $("#id_city option[value=" + i + "]").hide();
                    }
                })
            }
        </script>
        <form enctype="multipart/form-data" method="post">

            <div class="row">
                <div class="col-md-2">
                    {{ elebform.nty.errors }}
                    {{ elebform.nty.label_tag }}
                    {{ elebform.nty }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {{ elebform.province.errors }}
                    {{ elebform.province.label_tag }}
                    {{ elebform.province }}
                </div>
                <div class="col-md-3 col-md-offset-0">
                    {{ elebform.city.label_tag }}
                    {{ elebform.city }}
                    {{ elebform.city.errors }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {{ elebform.teachernum.errors }}
                    {{ elebform.teachernum.label_tag }}
                    {{ elebform.teachernum }}
                </div>
                <div class="col-md-3 col-md-offset-0">
                    {{ elebform.teamnum.errors }}
                    {{ elebform.teamnum.label_tag }}
                    {{ elebform.teamnum }}
                </div>
                <div class="col-md-3 col-md-offset-0">
                    {{ elebform.girlnum.errors }}
                    {{ elebform.girlnum.label_tag }}
                    {{ elebform.girlnum }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {{ elebform.starttime.errors }}
                    {{ elebform.starttime.label_tag }}
                    {{ elebform.starttime }}
                </div>
                <div class="col-md-3 col-md-offset-0">
                    {{ elebform.endtime.errors }}
                    {{ elebform.endtime.label_tag }}
                    {{ elebform.endtime }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {{ elebform.allo.errors }}
                    {{ elebform.allo.label_tag }}
                    {{ elebform.allo }}
                </div>
                <div class="col-md-3 col-md-offset-0">
                    {{ elebform.apply.errors }}
                    {{ elebform.apply.label_tag }}
                    {{ elebform.apply }}
                </div>
            </div>
            <div class="row">
                <hr>
                <div class="col-md-2 col-md-offset-6">

                    <input type="submit" value="确定" class="form-control"/>
                </div>
            </div>
        </form>
    </div>
    <script>
            var today = new Date();
            var format_td = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
            $('#id_starttime').datetimepicker({
                minView: 0,
                language: 'zh-CN',
                format: 'yyyy-mm-dd hh:ii',
                //todayBtn:  1,//今日按钮
                startDate: format_td,
                autoclose: 1,//选中关闭
                //todayHighlight : 1,
                //forceParse : 1,
            }).on('changeDate', function (ev) {
                var starttime = $('#id_starttime').val();
                $('#id_endtime').datetimepicker('setStartDate', starttime);
                $('#id_endtime').datetimepicker('hide')
            });
            $('#id_endtime').datetimepicker({
                minView: 0,
                language: 'zh-CN',
                format: 'yyyy-mm-dd hh:ii',
                autoclose: 1,//选中关闭
                //todayHighlight : 1,
                //forceParse : 1,
            })
        </script>
{% endblock %}

budget/templates/index.html
{% extends 'base.html' %}
{% block title %}
    ACM预算系统
{% endblock %}

{% block content %}
    {% for cnid in cnam %}
        <div class="panel panel-default">
            <div class="panel-heading">{{ cnid.name }}</div>
            <div class="panel-body">
                <ul>
                    {% if cnid.el_id %}
                        <li><a href="{% url 'selel' cnid.pk %}" >{{ cnid.name }}初始预算表</a></li>
                    {% endif %}
                    {% if cnid.ul_id %}
                        <li><a href="{% url 'selel' cnid.pk %}" >{{ cnid.name }}最终预算表</a></li>
                    {% endif %}
                    {% if cnid.ac_id %}
                        <li><a href="{% url 'selel' cnid.pk %}" >{{ cnid.name }}实际账单</a></li>
                    {% endif %}
                </ul>
            </div>
    </div>
        {% empty %}
        <h3 class="text-center" style="color: #76020c">还没有账目清单哟</h3>
    {% endfor %}


{% endblock %}